import { Router } from 'express';
import { authRouter as authRoutes } from './auth.routes';
import workerRoutes from './worker.routes';
import workerPortfolioRoutes from './worker-portfolio.routes';
import workerServicesRoutes from './worker-services.routes';
import workerAchievementsRoutes from './worker-achievements.routes';
import workerEarningsRoutes from './worker-earnings.routes';
import workerSubscriptionRoutes from './worker-subscription.routes';
import workerInnovationsRoutes from './worker-innovations.routes';
import verificationRoutes from './verification.routes';
import uploadRoutes from './upload.routes';
import addressRoutes from './address.routes';
import homeRoutes from './home.routes';
import referralRoutes from './referral.routes';
import subscriptionRoutes from './subscription.routes';
import negotiationRoutes from './negotiation.routes';
import emergencyRoutes from './emergency.routes';
import requestsRoutes from './requests.routes';
import jobRoutes from './job.routes';
import notificationRoutes from './notification.routes';
import trackingRoutes from './tracking.routes';
import bookingRoutes from './booking.routes';
import paymentRoutes from './payment.routes';
import reviewRoutes from './review.routes';
import chatRoutes from './chat.routes';
import cancellationRoutes from './cancellation.routes';
import adminRoutes from './admin.routes';
import superAdminRoutes from './super-admin.routes';
import supportRoutes from './support.routes';
import urgentRoutes from './urgent.routes';
import issueRoutes from './issue.routes';
import scopeChangeRoutes from './scope-change.routes';
import riskRoutes from './risk.routes';
import pricingAdminRoutes from './pricing-admin.routes';
import marketplaceAdminRoutes from './marketplace-admin.routes';
import guaranteeRoutes from './guarantee.routes';
import { disputeRouter } from './dispute.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/workers/portfolio', workerPortfolioRoutes);
router.use('/workers/achievements', workerAchievementsRoutes);
router.use('/workers/earnings', workerEarningsRoutes);
router.use('/workers/subscription', workerSubscriptionRoutes);
router.use('/workers/innovations', workerInnovationsRoutes);
router.use('/workers/verification', verificationRoutes); // must precede /workers
router.use('/workers/services', workerServicesRoutes); // must precede /workers
router.use('/workers', workerRoutes);
router.use('/addresses', addressRoutes);
router.use('/home', homeRoutes);
router.use('/referral', referralRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/negotiation', negotiationRoutes);
router.use('/emergency', emergencyRoutes);
router.use('/requests', requestsRoutes);
router.use('/jobs', jobRoutes);
router.use('/notifications', notificationRoutes);
router.use('/upload', uploadRoutes);
router.use('/tracking', trackingRoutes);
router.use('/bookings', bookingRoutes);
router.use('/cancellations', cancellationRoutes);
router.use('/payments', paymentRoutes);
router.use('/reviews', reviewRoutes);
router.use('/chat', chatRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/super', superAdminRoutes);
router.use('/support', supportRoutes);
router.use('/urgent', urgentRoutes);
router.use('/issues', issueRoutes);
router.use('/scope-changes', scopeChangeRoutes);
router.use('/risk', riskRoutes);
router.use('/admin-pricing', pricingAdminRoutes);
router.use('/admin-marketplace', marketplaceAdminRoutes);
router.use('/guarantee', guaranteeRoutes);
router.use('/disputes', disputeRouter);

export default router;
